### ISSUE TITLE
pancompare.py ipv6 / negate incorrectly handled

### ISSUE THREAD

**Issue by Nuttycomputer** [Nuttycomputer/pan-os-scripts#14]
At some version number, undetermined, panos stopped storing ipv6 addresses in the dataplane as 128 bit 0x... hex strings and instead now uses the more common representation of ipv6 as colon separated.

This has caused the logic to break and the address regex to incorrectly match items like:

0:0:0:0:0:0:0:0/101 and strip everything but 0/101 and hand it to netaddr which promptly lets you know via the following stack trace:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/netaddr/ip/__init__.py", line 923, in __init__
    implicit_prefix, flags)
  File "/usr/lib/python3.5/site-packages/netaddr/ip/__init__.py", line 816, in parse_ip_network
    % module.family_name)
netaddr.core.AddrFormatError: invalid prefix for IPv4 address!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pancompare.py", line 281, in <module>
    main()
  File "pancompare.py", line 276, in main
    completed_filter = filter_dataplane_rules(dataplane_raw, script_config.rule_filters)
  File "pancompare.py", line 223, in filter_dataplane_rules
    dataplane_rules[rule]['destination'] = convert_to_ipobject(dataplane_rules[rule]['destination'])
  File "pancompare.py", line 100, in convert_to_ipobject
    ip_address_objects = list(map(map_to_address, ip_addresses))
  File "pancompare.py", line 51, in map_to_address
    return netaddr.IPNetwork(ip).ipv6(True)
  File "/usr/lib/python3.5/site-packages/netaddr/ip/__init__.py", line 933, in __init__
    raise AddrFormatError('invalid IPNetwork %s' % addr)
netaddr.core.AddrFormatError: invalid IPNetwork 0/101
```

starting at pancompare.py line 75 and line 81

**Comment by Nuttycomputer** [comment]
Updated issue title, after some investigation into the test ruleset my particular crash is related to the destination being negated. Previously in the dataplane it would just say (negate) which it still does for regions but not straight ips
